### ISSUE TITLE
caiyunai.data_source.NetworkError: 网络错误

### ISSUE THREAD

**Issue by liffzaici** [MeetWq/nonebot-plugin-caiyunai#1]
请问这种报错是我的网络问题吗
![7 Y4 OH6B38HB 436J@JH4E](https://user-images.githubusercontent.com/98678215/151959020-18a7068c-525a-44b2-96c0-969840f1e5ad.png)

**Comment by MeetWq** [comment]
可能是你的网络问题，也可能是彩云小梦网站的问题，如果不是很频繁的话多试几次就行了

**Comment by Superskyyy** [comment]
同样出现了这个问题 重复出现 好像不会恢复，是不是api改了。

**Comment by MeetWq** [comment]
fix in #2
